// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/puller.proto

package pullerv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// SubscribeRequest configures a subscription to the event stream.
type SubscribeRequest struct {
	// Consumer identifier for logging/monitoring only.
	// Does not affect event delivery.
	ConsumerId string `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	// Progress marker from last processed event.
	// Return events AFTER this marker (exclusive).
	// Empty = start from current head (no historical events).
	After string `protobuf:"bytes,2,opt,name=after,proto3" json:"after,omitempty"`
	// Enable catch-up coalescing when consumer is behind.
	// When enabled and consumer is catching up, multiple events
	// for the same document may be merged.
	CoalesceOnCatchUp    bool     `protobuf:"varint,3,opt,name=coalesce_on_catch_up,json=coalesceOnCatchUp,proto3" json:"coalesce_on_catch_up,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3b6dab2006ffd1d, []int{0}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetConsumerId() string {
	if m != nil {
		return m.ConsumerId
	}
	return ""
}

func (m *SubscribeRequest) GetAfter() string {
	if m != nil {
		return m.After
	}
	return ""
}

func (m *SubscribeRequest) GetCoalesceOnCatchUp() bool {
	if m != nil {
		return m.CoalesceOnCatchUp
	}
	return false
}

// PullerEvent is the top-level wrapper for events emitted by the Puller service.
type PullerEvent struct {
	// The actual change event.
	ChangeEvent *ChangeEvent `protobuf:"bytes,1,opt,name=change_event,json=changeEvent,proto3" json:"change_event,omitempty"`
	// Current progress marker (opaque string).
	// Consumer should save this value and pass it as 'after'
	// when reconnecting to resume from this position.
	Progress             string   `protobuf:"bytes,2,opt,name=progress,proto3" json:"progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullerEvent) Reset()         { *m = PullerEvent{} }
func (m *PullerEvent) String() string { return proto.CompactTextString(m) }
func (*PullerEvent) ProtoMessage()    {}
func (*PullerEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3b6dab2006ffd1d, []int{1}
}

func (m *PullerEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullerEvent.Unmarshal(m, b)
}
func (m *PullerEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullerEvent.Marshal(b, m, deterministic)
}
func (m *PullerEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullerEvent.Merge(m, src)
}
func (m *PullerEvent) XXX_Size() int {
	return xxx_messageInfo_PullerEvent.Size(m)
}
func (m *PullerEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PullerEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PullerEvent proto.InternalMessageInfo

func (m *PullerEvent) GetChangeEvent() *ChangeEvent {
	if m != nil {
		return m.ChangeEvent
	}
	return nil
}

func (m *PullerEvent) GetProgress() string {
	if m != nil {
		return m.Progress
	}
	return ""
}

// ChangeEvent represents a normalized change event from the database.
type ChangeEvent struct {
	// Unique event identifier.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Tenant identifier.
	Tenant string `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// Mongo collection name.
	MgoColl string `protobuf:"bytes,3,opt,name=mgo_coll,json=mgoColl,proto3" json:"mgo_coll,omitempty"`
	// Mongo document identifier.
	MgoDocId string `protobuf:"bytes,4,opt,name=mgo_doc_id,json=mgoDocId,proto3" json:"mgo_doc_id,omitempty"`
	// Operation type: "insert", "update", "replace", or "delete".
	OpType string `protobuf:"bytes,5,opt,name=op_type,json=opType,proto3" json:"op_type,omitempty"`
	// Full document after the change (JSON encoded storage.Document).
	// Empty for delete operations.
	FullDoc []byte `protobuf:"bytes,6,opt,name=full_doc,json=fullDoc,proto3" json:"full_doc,omitempty"`
	// Description of update changes (JSON encoded).
	// Only present for update operations.
	UpdateDesc []byte `protobuf:"bytes,7,opt,name=update_desc,json=updateDesc,proto3" json:"update_desc,omitempty"`
	// MongoDB cluster timestamp.
	ClusterTime *ClusterTime `protobuf:"bytes,8,opt,name=cluster_time,json=clusterTime,proto3" json:"cluster_time,omitempty"`
	// Unix timestamp in milliseconds when the event was received.
	Timestamp int64 `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Transaction number if part of a transaction.
	TxnNumber int64 `protobuf:"varint,10,opt,name=txn_number,json=txnNumber,proto3" json:"txn_number,omitempty"`
	// Backend identifier.
	Backend              string   `protobuf:"bytes,11,opt,name=backend,proto3" json:"backend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeEvent) Reset()         { *m = ChangeEvent{} }
func (m *ChangeEvent) String() string { return proto.CompactTextString(m) }
func (*ChangeEvent) ProtoMessage()    {}
func (*ChangeEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3b6dab2006ffd1d, []int{2}
}

func (m *ChangeEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeEvent.Unmarshal(m, b)
}
func (m *ChangeEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeEvent.Marshal(b, m, deterministic)
}
func (m *ChangeEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeEvent.Merge(m, src)
}
func (m *ChangeEvent) XXX_Size() int {
	return xxx_messageInfo_ChangeEvent.Size(m)
}
func (m *ChangeEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeEvent proto.InternalMessageInfo

func (m *ChangeEvent) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *ChangeEvent) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *ChangeEvent) GetMgoColl() string {
	if m != nil {
		return m.MgoColl
	}
	return ""
}

func (m *ChangeEvent) GetMgoDocId() string {
	if m != nil {
		return m.MgoDocId
	}
	return ""
}

func (m *ChangeEvent) GetOpType() string {
	if m != nil {
		return m.OpType
	}
	return ""
}

func (m *ChangeEvent) GetFullDoc() []byte {
	if m != nil {
		return m.FullDoc
	}
	return nil
}

func (m *ChangeEvent) GetUpdateDesc() []byte {
	if m != nil {
		return m.UpdateDesc
	}
	return nil
}

func (m *ChangeEvent) GetClusterTime() *ClusterTime {
	if m != nil {
		return m.ClusterTime
	}
	return nil
}

func (m *ChangeEvent) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ChangeEvent) GetTxnNumber() int64 {
	if m != nil {
		return m.TxnNumber
	}
	return 0
}

func (m *ChangeEvent) GetBackend() string {
	if m != nil {
		return m.Backend
	}
	return ""
}

// ClusterTime represents MongoDB cluster timestamp for ordering.
type ClusterTime struct {
	// Seconds since Unix epoch.
	T uint32 `protobuf:"varint,1,opt,name=t,proto3" json:"t,omitempty"`
	// Increment within the second (for ordering multiple events).
	I                    uint32   `protobuf:"varint,2,opt,name=i,proto3" json:"i,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterTime) Reset()         { *m = ClusterTime{} }
func (m *ClusterTime) String() string { return proto.CompactTextString(m) }
func (*ClusterTime) ProtoMessage()    {}
func (*ClusterTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3b6dab2006ffd1d, []int{3}
}

func (m *ClusterTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterTime.Unmarshal(m, b)
}
func (m *ClusterTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterTime.Marshal(b, m, deterministic)
}
func (m *ClusterTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterTime.Merge(m, src)
}
func (m *ClusterTime) XXX_Size() int {
	return xxx_messageInfo_ClusterTime.Size(m)
}
func (m *ClusterTime) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterTime.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterTime proto.InternalMessageInfo

func (m *ClusterTime) GetT() uint32 {
	if m != nil {
		return m.T
	}
	return 0
}

func (m *ClusterTime) GetI() uint32 {
	if m != nil {
		return m.I
	}
	return 0
}

func init() {
	proto.RegisterType((*SubscribeRequest)(nil), "syntrix.puller.v1.SubscribeRequest")
	proto.RegisterType((*PullerEvent)(nil), "syntrix.puller.v1.PullerEvent")
	proto.RegisterType((*ChangeEvent)(nil), "syntrix.puller.v1.ChangeEvent")
	proto.RegisterType((*ClusterTime)(nil), "syntrix.puller.v1.ClusterTime")
}

func init() {
	proto.RegisterFile("api/proto/puller.proto", fileDescriptor_b3b6dab2006ffd1d)
}

var fileDescriptor_b3b6dab2006ffd1d = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x95, 0x8d, 0x2d, 0xed, 0x4b, 0x2b, 0x31, 0x6b, 0x1a, 0x61, 0x1a, 0x50, 0x95, 0x4b,
	0xb9, 0x34, 0xb4, 0x70, 0xe3, 0x04, 0x2d, 0x87, 0x5e, 0x00, 0x79, 0xe3, 0xc2, 0x25, 0x4a, 0x9c,
	0xb7, 0x34, 0x9a, 0x63, 0x1b, 0xdb, 0xa9, 0x5a, 0x3e, 0x31, 0x1f, 0x03, 0xd9, 0xc9, 0xd6, 0x0a,
	0xc6, 0x2d, 0xbf, 0xf7, 0xcf, 0xff, 0x3d, 0xbf, 0xe7, 0x67, 0xb8, 0xc8, 0x54, 0x95, 0x28, 0x2d,
	0xad, 0x4c, 0x54, 0xc3, 0x39, 0xea, 0xa9, 0x07, 0x72, 0x66, 0x76, 0xc2, 0xea, 0x6a, 0x3b, 0xed,
	0xa2, 0x9b, 0xd9, 0xf8, 0x17, 0x3c, 0xbd, 0x6e, 0x72, 0xc3, 0x74, 0x95, 0x23, 0xc5, 0x9f, 0x0d,
	0x1a, 0x4b, 0x5e, 0x41, 0xc4, 0xa4, 0x30, 0x4d, 0x8d, 0x3a, 0xad, 0x8a, 0x38, 0x18, 0x05, 0x93,
	0x3e, 0x85, 0xfb, 0xd0, 0xaa, 0x20, 0xe7, 0x70, 0x92, 0xdd, 0x5a, 0xd4, 0xf1, 0x91, 0x97, 0x5a,
	0x20, 0x09, 0x9c, 0x33, 0x99, 0x71, 0x34, 0x0c, 0x53, 0x29, 0x52, 0x96, 0x59, 0xb6, 0x4e, 0x1b,
	0x15, 0x1f, 0x8f, 0x82, 0x49, 0x8f, 0x9e, 0xdd, 0x6b, 0x5f, 0xc5, 0xc2, 0x29, 0xdf, 0xd5, 0x98,
	0x43, 0xf4, 0xcd, 0x1f, 0xe4, 0xf3, 0x06, 0x85, 0x25, 0x1f, 0x61, 0xc0, 0xd6, 0x99, 0x28, 0x31,
	0x45, 0xc7, 0xbe, 0x6e, 0x34, 0x7f, 0x39, 0xfd, 0xe7, 0xd0, 0xd3, 0x85, 0xff, 0xcd, 0xbb, 0x68,
	0xc4, 0xf6, 0x40, 0x2e, 0xa1, 0xa7, 0xb4, 0x2c, 0x35, 0x1a, 0xd3, 0x9d, 0xed, 0x81, 0xc7, 0xbf,
	0x8f, 0x20, 0x3a, 0x30, 0x92, 0xe7, 0xd0, 0xf3, 0x75, 0xf6, 0x2d, 0x86, 0x9e, 0x57, 0x05, 0xb9,
	0x80, 0x53, 0x8b, 0x22, 0x13, 0xb6, 0x4b, 0xd2, 0x91, 0xb3, 0xd4, 0xa5, 0x4c, 0x99, 0xe4, 0xdc,
	0x77, 0xd5, 0xa7, 0x61, 0x5d, 0xca, 0x85, 0xe4, 0x9c, 0x5c, 0x01, 0x38, 0xa9, 0x90, 0xcc, 0xe5,
	0x7b, 0xd2, 0xd6, 0xae, 0x4b, 0xb9, 0x94, 0x6c, 0x55, 0x90, 0x67, 0x10, 0x4a, 0x95, 0xda, 0x9d,
	0xc2, 0xf8, 0xa4, 0xcd, 0x28, 0xd5, 0xcd, 0x4e, 0xa1, 0xcb, 0x78, 0xdb, 0x70, 0xee, 0x7c, 0xf1,
	0xe9, 0x28, 0x98, 0x0c, 0x68, 0xe8, 0x78, 0x29, 0x99, 0xbb, 0x85, 0x46, 0x15, 0x99, 0xc5, 0xb4,
	0x40, 0xc3, 0xe2, 0xd0, 0xab, 0xd0, 0x86, 0x96, 0x68, 0x98, 0x9f, 0x17, 0x6f, 0x8c, 0x45, 0x9d,
	0xda, 0xaa, 0xc6, 0xb8, 0xf7, 0xff, 0x79, 0xb5, 0xbf, 0xdd, 0x54, 0x35, 0xd2, 0x88, 0xed, 0x81,
	0x5c, 0x41, 0xdf, 0x59, 0x8d, 0xcd, 0x6a, 0x15, 0xf7, 0x47, 0xc1, 0xe4, 0x98, 0xee, 0x03, 0xe4,
	0x05, 0x80, 0xdd, 0x8a, 0x54, 0x34, 0x75, 0x8e, 0x3a, 0x86, 0x4e, 0xde, 0x8a, 0x2f, 0x3e, 0x40,
	0x62, 0x08, 0xf3, 0x8c, 0xdd, 0xa1, 0x28, 0xe2, 0xa8, 0x1d, 0x46, 0x87, 0xe3, 0x37, 0x10, 0x1d,
	0x94, 0x24, 0x03, 0x08, 0xda, 0xdb, 0x1c, 0xd2, 0xc0, 0x3a, 0xaa, 0xfc, 0x5c, 0x87, 0x34, 0xa8,
	0xe6, 0x0c, 0x86, 0xed, 0x0e, 0x5c, 0xa3, 0xde, 0x54, 0x0c, 0x09, 0x85, 0xfe, 0xc3, 0x42, 0x92,
	0xd7, 0x8f, 0x34, 0xf3, 0xf7, 0xba, 0x5e, 0x3e, 0xd6, 0xf1, 0xc1, 0x5e, 0xbd, 0x0d, 0x3e, 0xbd,
	0xff, 0x31, 0x2f, 0x2b, 0xbb, 0x6e, 0xf2, 0x29, 0x93, 0x75, 0xc2, 0x64, 0x81, 0x56, 0xe3, 0x5d,
	0xd2, 0xd9, 0x12, 0xff, 0x5a, 0xbc, 0x21, 0xd9, 0xcc, 0x3e, 0xb4, 0x5f, 0x9b, 0x59, 0x7e, 0xea,
	0x1f, 0xcd, 0xbb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x66, 0x16, 0x34, 0x98, 0x4e, 0x03, 0x00,
	0x00,
}
