// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/proto/puller.proto

package pullerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PullerService_Subscribe_FullMethodName = "/syntrix.puller.v1.PullerService/Subscribe"
)

// PullerServiceClient is the client API for PullerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PullerService provides access to the merged event stream from all backends.
// Consumers subscribe to events and manage their own progress.
type PullerServiceClient interface {
	// Subscribe to merged event stream from all backends.
	// Events are delivered in order within each backend, merged across backends.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullerEvent], error)
}

type pullerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPullerServiceClient(cc grpc.ClientConnInterface) PullerServiceClient {
	return &pullerServiceClient{cc}
}

func (c *pullerServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullerEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PullerService_ServiceDesc.Streams[0], PullerService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, PullerEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PullerService_SubscribeClient = grpc.ServerStreamingClient[PullerEvent]

// PullerServiceServer is the server API for PullerService service.
// All implementations must embed UnimplementedPullerServiceServer
// for forward compatibility.
//
// PullerService provides access to the merged event stream from all backends.
// Consumers subscribe to events and manage their own progress.
type PullerServiceServer interface {
	// Subscribe to merged event stream from all backends.
	// Events are delivered in order within each backend, merged across backends.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[PullerEvent]) error
	mustEmbedUnimplementedPullerServiceServer()
}

// UnimplementedPullerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPullerServiceServer struct{}

func (UnimplementedPullerServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[PullerEvent]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedPullerServiceServer) mustEmbedUnimplementedPullerServiceServer() {}
func (UnimplementedPullerServiceServer) testEmbeddedByValue()                       {}

// UnsafePullerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PullerServiceServer will
// result in compilation errors.
type UnsafePullerServiceServer interface {
	mustEmbedUnimplementedPullerServiceServer()
}

func RegisterPullerServiceServer(s grpc.ServiceRegistrar, srv PullerServiceServer) {
	// If the following call panics, it indicates UnimplementedPullerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PullerService_ServiceDesc, srv)
}

func _PullerService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PullerServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, PullerEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PullerService_SubscribeServer = grpc.ServerStreamingServer[PullerEvent]

// PullerService_ServiceDesc is the grpc.ServiceDesc for PullerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PullerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "syntrix.puller.v1.PullerService",
	HandlerType: (*PullerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _PullerService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/puller.proto",
}
